#! /bin/bash
# SPDX-License-Identifier: Apache-2.0
# (c) Copyright 2006 - 2022 Xilinx, Inc. All rights reserved.
#
# Helper scripts/to build sfc-linux-net as part of TE build
#

MAKE_ARGS="${@}"

set -e

LIB_MOD_DIR="lib/modules/$(uname -r)"

rsync -av --delete --exclude='*.o' --exclude='*.mod.c' --exclude='*.ko' \
    --exclude='*.mod' --exclude='*.cmd' --exclude='*.d' --exclude='*.a' \
    --exclude=autocompat.h --exclude=modules.order \
    --exclude=Module.symvers --exclude=.kpath --exclude=build \
    "${EXT_SOURCES}"/ .

if [ -f ./scripts/onload ] ; then
    # This is driver from Onload repository

    export PATH=$PATH:${PWD}/scripts/

    ./scripts/mmakebuildtree --driver && \
        drv_dir=$(./scripts/mmaketool --driverbuild) && \
        make -C ./build/${drv_dir} ${MAKE_ARGS}
    BUILD_RC=$?
else
    # This is driver from sfc-linux-net repository

    # Unfortunately parallel build looks unstable
    make ${MAKE_ARGS}
    BUILD_RC=$?

    # If we set KPATH, we are likely building for a different kernel
    # This means the install path needs to be adjusted
    if [[ "${BUILD_RC}" == 0 && "${MAKE_ARGS}" == *"KPATH="* ]]; then
        VERMAGIC=$(modinfo -F vermagic ./drivers/net/ethernet/sfc/sfc.ko | cut -f1 -d' ')
        if [ -n "${VERMAGIC}" ]; then
            LIB_MOD_DIR="lib/modules/${VERMAGIC}"
        fi
    fi
fi

if [ "${BUILD_RC}" -eq 0 ] ; then
    for ta_type in ${TE_TA_TYPES} ; do
        DST="${TE_AGENTS_INST}/${ta_type}/${LIB_MOD_DIR}"
        mkdir -p "$DST"
        find . -name '*.ko' -type f -exec cp -a {} "${DST}/" \;
    done
    exit 0
else
    exit 1
fi
