#! /bin/bash
# SPDX-License-Identifier: Apache-2.0
# (c) Copyright 2006 - 2022 Xilinx, Inc. All rights reserved.
#
# Helper scripts/to build sfc-linux-net as part of TE build
#

MAKE_ARGS="${@}"

set -e

rsync -av --delete --exclude='*.o' --exclude='*.mod.c' --exclude='*.ko' \
    --exclude='*.mod' --exclude='*.cmd' --exclude='*.d' --exclude='*.a' \
    --exclude=autocompat.h --exclude=config.h --exclude=modules.order \
    --exclude=Module.symvers --exclude=.kpath "${EXT_SOURCES}"/ .

# Unfortunatley parallel build looks unstable
if make ${MAKE_ARGS} ; then
    for ta_type in ${TE_TA_TYPES} ; do
        find . -name '*.ko' -exec cp -a {} "${TE_AGENTS_INST}/${ta_type}/" \;
    done
    exit 0
else
    exit 1
fi
